version: '3'

services:
  db:
    image: mysql:5.7-debian
    command: --init-file /init/web.sql
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./init:/init
    restart: always
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy