version: '3'

services:
  db:
    image: mysql:5.7-debian
    command: --init-file /init/web.sql
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
      - ./init:/init
    restart: always
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 20 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started